spring:
  profiles:
    active: dao
#  dubbo:
#    application:
#      name: daocao-manager-service
#    registry:
#      address: zookeeper://192.168.25.128:2181
#    protocol:
#      name: dubbo
#      port: 20881
#    scan: com.daocao.managerservice.impl
#    server: true
dubbo:
  application:
    name: daocao-manager-service
  protocol:
    name: dubbo
    port: "20881"
  registry:
    address: zookeeper://192.168.25.128:2181
  scan:
    base-packages: com.daocao.managerservice.impl