server:
    port: 8082
    servlet:
        session:
            cookie:
                name: USER_SESSION

dubbo:
    application:
        name: daocao-user-web
    registry:
        address: zookeeper://192.168.25.128:2181
    protocol:
        name: dubbo

fdfs:
    so-timeout: 1500
    connect-timeout: 600
    tracker-list: 192.168.25.133:22122
    pool:
        jmx-enabled: false

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 15MB

fastdfs:
    host: 192.168.25.133/

security:
    oauth2:
        client:
            client-id: daocao_client
            client-secret: daocao_secret
            access-token-uri: http://localhost:9100/oauth/token
            user-authorization-uri: http://localhost:9100/oauth/authorize
        resource:
            user-info-uri: http://localhost:9100/user