server:
  port: 8083

dubbo:
  application:
    name: daocao-page-web
  registry:
    address: zookeeper://192.168.25.128:2181
  protocol:
    name: dubbo

spring:
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
#    cache: false  #关闭模板缓存，方便测试
#      settings:
#        template_update_delay: 0  #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

directPath: H:\\编程空间\\IDEA\\DaoCao\\DaoCaoBook\\daocao-parent\\web\\daocao-page-web\\src\\main\\resources\\static\\