server:
    port: 8085
    servlet:
        session:
            cookie:
                name: CART_SESSION

dubbo:
    application:
        name: daocao-cart-web
    registry:
        address: zookeeper://192.168.25.128:2181
    protocol:
        name: dubbo

security:
    oauth2:
        client:
            client-id: daocao_client
            client-secret: daocao_secret
            access-token-uri: http://localhost:9100/oauth/token
            user-authorization-uri: http://localhost:9100/oauth/authorize
        resource:
            user-info-uri: http://localhost:9100/user