spring:
  datasource:
    username: root
    password: zxc987123.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daocao?characterEncoding=utf-8&useUnicode=true&useSSL=false
      &serverTimezone=Hongkong&allowPublicKeyRetrieval=true

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.varg.dubboproductor.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true