spring:
  redis:
    host: 192.168.25.128
    port: 6379
  profiles:
    active: dao

dubbo:
  application:
    name: daocao-cart-service
  protocol:
    name: dubbo
    port: "20884"
  registry:
    address: zookeeper://192.168.25.128:2181
  scan:
    base-packages: com.daocao.cartservice.impl